[default.extend-identifiers]

[default.extend-words]

[files]
ignore-vcs = true
ignore-files = true
ignore-dot = true
extend-exclude = ["docs/dcs/src/*","docs/dcs/partials/*","docs/_site/*"]

[default]
locale = "en-us"
